MATRIX 

In [6]:
import numpy as np 
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
print(a)

[[1. 2.]
 [3. 4.]]


In [14]:
import numpy as np
 
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats 
print("A=", A) 
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers 
print("A=", A)

A= [[1.1 2.  3. ]
 [3.  4.  5. ]]
A= [[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


Vector

In [15]:
import numpy as np 
a = np.array([1.0, 2.0, 3.0, 4.0]) 
print(a)

[1. 2. 3. 4.]


In [17]:
import numpy as np 
v = np.array([[1],[2],[3]]) 
print(v)

[[1]
 [2]
 [3]]


Matrrix Addition 

In [18]:
import numpy as np 
A = np.array([1, 3, 5, 7]) 
B = np.array([1, 3, 5, 7]) 
C = A + B 
print("C=", C)

C= [ 2  6 10 14]


In [19]:
import numpy as np 
A = np.array([[1], [3], [5], [7]]) 
B = np.array ([[1], [3], [5], [7]]) 
C = A + B 
print("C=", C)

C= [[ 2]
 [ 6]
 [10]
 [14]]


In [22]:
import numpy as np 
A = np.array([[2, 4], [5, -6]]) 
B = np.array([[9, -3], [3, 6]]) 
C = A + B      # element wise addition 
print(C)

[[11  1]
 [ 8  0]]


Transpose of the Matrix

In [24]:
import numpy as np 
v = np.array([1, 2, 3]) 
print(v)
print(v.transpose())

[1 2 3]
[1 2 3]


In [28]:
import numpy as np 
v = np.array([[1], [2], [3]]) 
print(v)
print("transpose")
print(v.transpose())

[[1]
 [2]
 [3]]
transpose
[[1 2 3]]


In [39]:
import numpy as np
A = np.array([[1, 1], [2, 1], [3, -3]])
print (A) 
print ("Transpose")
print(A.transpose())

[[ 1  1]
 [ 2  1]
 [ 3 -3]]
Transpose
[[ 1  2  3]
 [ 1  1 -3]]


Matrix Multiplication by scalar

In [40]:
# Scalar Multiplication of Vector 
import numpy as np 
V1 = np.array([4, 3, 2]) 
c =2 
print("The Vector V1 = ", V1) 
print("The Vector cxV = ", c*V1)

The Vector V1 =  [4 3 2]
The Vector cxV =  [8 6 4]


Matrix Multiplication

In [43]:
# Outer Product 
import numpy as np 
a = np.array([2, 4, 8, 7, 7])
b = np.array([2, 3, 1, 7, 8]) #outer product in both order 
opab = np.outer(a,b)
opba = np.outer(b,a) 
print('\n\n---A---\n', a) 
print('\n\n---B---\n', b) 
print('\n\nOuter Product as A.B : ', opab) 
print('\n\nOuter Product as A.B : ', opba)



---A---
 [2 4 8 7 7]


---B---
 [2 3 1 7 8]


Outer Product as A.B :  [[ 4  6  2 14 16]
 [ 8 12  4 28 32]
 [16 24  8 56 64]
 [14 21  7 49 56]
 [14 21  7 49 56]]


Outer Product as A.B :  [[ 4  8 16 14 14]
 [ 6 12 24 21 21]
 [ 2  4  8  7  7]
 [14 28 56 49 49]
 [16 32 64 56 56]]


In [77]:
import numpy as np
A = np.array([[3, 6, 7], [5, -3, 0]]) 
print("A=",A)
B = np.array([[1, 1], [2, 1], [3, -3]]) 
print("B=",B)
D = A.dot(B)  
print("D=", D) 
P = np.array([[3, 6, 7], [5, -3, 0]]) 
Q = np.array([[1, 1, 2], [2, 1, 4]]) 
R = P * Q # elements-wise multiplication # not matrix multiplication 
print("R=", R)

A= [[ 3  6  7]
 [ 5 -3  0]]
B= [[ 1  1]
 [ 2  1]
 [ 3 -3]]
[[ 36 -12]
 [ -1   2]]
D= [[ 36 -12]
 [ -1   2]]
R= [[ 3  6 14]
 [10 -3  0]]


Vector Multiplication

In [49]:
# Vector Multiplication 
import numpy as np 
V1 = np.array([4, 5, 6, 7])
V2 = np.array([[4], [5], [6],[7]]) 
V3 = V1.transpose() 
R1 = V1.dot(V2) 
print(type(R1)) 
print(R1) 
R2 = V1.dot(V1) 
print(type(R2))
print(R2)

<class 'numpy.ndarray'>
[126]
<class 'numpy.int64'>
126


Diagonal Matrix 

In [51]:
import numpy as np 
x = np.arange(9).reshape((3,3))
print (x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
import numpy as np
x = np.arange(9).reshape((3,3))
diag= np.diag(x, k=1) # array([1, 5]) 
print (diag)
diag2= np.diag(x, k=-1) #array([3, 7]) 
print (diag2)
y = np.diag(np.diag(x)) 
print (y)
z = np.diag([5, 6, 7])

[2]
[3 7]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [64]:
# Identity Matrix Property (I^k = I) 
import numpy as np 
I = np.eye(4) 
print("\n---I(4x4)---\n", I) 
k = 14 
Ik = I 
for i in range(14):Ik =I*Ik
print('\n\n--- I^k ----\n', Ik)


---I(4x4)---
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


--- I^k ----
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [66]:
# Identity Matrix Property (AI = A) 
import numpy as np 
I = np.eye(3) 
print("---Matrix I---\n", I) 
A = np.array([[2,3,4], [3,45,8], [4,8,78]]) 
print("---Matrix A---\n", A) 
ai = np.matmul(A, I) 
print('Identity Matrix Property I.A', ai) 
if ai.all() == A.all(): 
  print("AI = A")

---Matrix I---
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---Matrix A---
 [[ 2  3  4]
 [ 3 45  8]
 [ 4  8 78]]
Identity Matrix Property I.A [[ 2.  3.  4.]
 [ 3. 45.  8.]
 [ 4.  8. 78.]]
AI = A


Determinantes

In [67]:
# Finding determinant 
import numpy as np 
M = np.array([[2,3,4], [3,45,8], [4,8,78]]) 
print("---Matrix A---\n", M) 
det_A = np.linalg.det(M) 
print("The determinant of matrix A : ", det_A) 
M = np.array([[2,3,4], [3,14,8], [14,8,7]]) 
print("\n\n---Matrix B---\n", M) 
det_B = np.linalg.det(M) 
print("The determinant of matrix B : ", det_B)

---Matrix A---
 [[ 2  3  4]
 [ 3 45  8]
 [ 4  8 78]]
The determinant of matrix A :  5661.9999999999945


---Matrix B---
 [[ 2  3  4]
 [ 3 14  8]
 [14  8  7]]
The determinant of matrix B :  -347.00000000000006


inverse of Matrix 

In [68]:
# Inverse of a Matrix 
import numpy as np 
M = np.array([[2, 3, 4], [3, 5, 8], [4, 8, 7]]) 
print("---Matrix A---\n", M) 
ai = np.linalg.inv(M) 
print('\n\nInverse of A as ----\n', ai)

---Matrix A---
 [[2 3 4]
 [3 5 8]
 [4 8 7]]


Inverse of A as ----
 [[ 3.22222222 -1.22222222 -0.44444444]
 [-1.22222222  0.22222222  0.44444444]
 [-0.44444444  0.44444444 -0.11111111]]


Eigan Value and Eigan vector 

In [76]:
# Eigen Values and Eigen Vectors of a Matrix 
import numpy as np 
import scipy.linalg as la 
n = 4 
P = np.random.randint(0,10,(n,n)) 
print(P) #Create the symmetric matrix S=P.P' 
S = P @ P.T  # @ represents matrix multipllication and .T transpose
print(S) #Let's unpack the eigenvalues and eigenvectors of S 
evals, evecs = la.eig(S) 
print(evals)
 #The eigenvalues all have zero imaginary part and #so they are indeed real numbers:
evals = evals.real 
print(evals) #The corresponding eigenvectors of A are: 
print(evecs) #Let's check that the eigenvectors are orthogonal to each other:
v1 = evecs[:,0] # First column is the first eigenvector print(v1)
v2 = evecs[:,1] # Second column is the second eigenvector print(v2)
print (v1 @v2)

[[4 5 2 4]
 [5 4 8 5]
 [6 6 6 9]
 [0 8 8 6]]
[[ 61  76 102  80]
 [ 76 130 147 126]
 [102 147 189 150]
 [ 80 126 150 164]]
[497.24562896+0.j  30.5180395 +0.j   3.03758929+0.j  13.19874226+0.j]
[497.24562896  30.5180395    3.03758929  13.19874226]
[[-0.32522729 -0.31665804 -0.71084092  0.53727095]
 [-0.49274448 -0.13343562 -0.3187372  -0.79862657]
 [-0.60343597 -0.45170262  0.62670503  0.19766279]
 [-0.53599918  0.82333915  0.01877709  0.18564735]]
-7.778209039992839e-17
